/*
 * MIT License
 *
 * Copyright (c) 2025 DNV
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * @file VISVersionsGenerator.cpp
 * @brief VIS version header generator tool
 * @details Generates VISVersions.h from embedded VIS resource files
 */

#include <EmbeddedResource/EmbeddedResource.h>

#include <nfx/string/StringBuilder.h>
#include <nfx/string/Utils.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using namespace dnv::vista::sdk;

static bool generateVISVersionHeader( const std::vector<std::string>& versions, const fs::path& outputPath, std::string_view sdkVersion )
{
	auto lease = nfx::string::StringBuilderPool::lease( 8192 );
	auto sb = lease.create();

	// MIT License header
	sb.append( "/*\n" );
	sb.append( " * MIT License\n" );
	sb.append( " *\n" );
	sb.append( " * Copyright (c) 2025 DNV\n" );
	sb.append( " *\n" );
	sb.append( " * Permission is hereby granted, free of charge, to any person obtaining a copy\n" );
	sb.append( " * of this software and associated documentation files (the \"Software\"), to deal\n" );
	sb.append( " * in the Software without restriction, including without limitation the rights\n" );
	sb.append( " * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n" );
	sb.append( " * copies of the Software, and to permit persons to whom the Software is\n" );
	sb.append( " * furnished to do so, subject to the following conditions:\n" );
	sb.append( " *\n" );
	sb.append( " * The above copyright notice and this permission notice shall be included in all\n" );
	sb.append( " * copies or substantial portions of the Software.\n" );
	sb.append( " *\n" );
	sb.append( " * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n" );
	sb.append( " * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n" );
	sb.append( " * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n" );
	sb.append( " * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n" );
	sb.append( " * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n" );
	sb.append( " * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n" );
	sb.append( " * SOFTWARE.\n" );
	sb.append( " */\n" );
	sb.append( "\n" );
	sb.append( "/**\n" );
	sb.append( " * @file VISVersions.h\n" );
	sb.append( " * @brief Type-safe enumeration of VIS versions and string conversion utilities\n" );
	sb.append( " * @details AUTO-GENERATED FILE - DO NOT EDIT - " );
	std::format_to( std::back_inserter( sb ), "Generated by: VISVersionsGenerator (vista-sdk-cpp v{})\n", sdkVersion );
	sb.append( " */\n" );
	sb.append( "\n" );

	// Includes
	sb.append( "#pragma once\n\n" );
	sb.append( "#include <array>\n" );
	sb.append( "#include <optional>\n" );
	sb.append( "#include <stdexcept>\n" );
	sb.append( "#include <string>\n" );
	sb.append( "#include <string_view>\n\n" );
	sb.append( "namespace dnv::vista::sdk\n" );
	sb.append( "{\n" );

	// Enum declaration
	sb.append( "/**\n" );
	sb.append( " * @brief Enumeration of VIS versions\n" );
	sb.append( " */\n" );
	sb.append( "enum class VISVersion : std::uint16_t\n" );
	sb.append( "{\n" );

	for ( const auto& version : versions )
	{
		std::string enumName = version;
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "    v{},\n", enumName );
	}

	sb.append( "};\n\n" );

	// VISVersions namespace
	sb.append( "/**\n" );
	sb.append( " * @brief VIS version utilities and extension methods\n" );
	sb.append( " */\n" );
	sb.append( "namespace VISVersions\n" );
	sb.append( "{\n" );

	// All versions array
	sb.append( "/**\n" );
	sb.append( " * @brief Array of all VIS versions enum values\n" );
	sb.append( " * @return Array containing all VIS version enum values\n" );
	sb.append( " */\n" );
	std::format_to( std::back_inserter( sb ), "constexpr std::array<VISVersion, {}> all()\n", versions.size() );
	sb.append( "{\n" );
	sb.append( "    return {\n" );

	for ( size_t i = 0; i < versions.size(); ++i )
	{
		std::string enumName = versions[i];
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "        VISVersion::v{},\n", enumName );
	}

	sb.append( "    };\n" );
	sb.append( "}\n\n" );

	// latest function
	sb.append( "/**\n" );
	sb.append( " * @brief Get the latest available VIS version\n" );
	sb.append( " * @return The latest VIS version\n" );
	sb.append( " */\n" );
	sb.append( "constexpr VISVersion latest() noexcept\n" );
	sb.append( "{\n" );
	sb.append( "    constexpr auto versions = all();\n" );
	sb.append( "    return versions.back();\n" );
	sb.append( "}\n\n" );

	// isValid function
	sb.append( "/**\n" );
	sb.append( " * @brief Check if a VisVersion is valid\n" );
	sb.append( " * @param version The version to check\n" );
	sb.append( " * @return true if valid, false otherwise\n" );
	sb.append( " */\n" );
	sb.append( "constexpr bool isValid( VISVersion version )\n" );
	sb.append( "{\n" );
	sb.append( "    switch ( version )\n" );
	sb.append( "    {\n" );

	for ( const auto& version : versions )
	{
		std::string enumName = version;
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "        case VISVersion::v{}:\n", enumName );
	}

	sb.append( "        return true;\n" );
	sb.append( "    default:\n" );
	sb.append( "        return false;\n" );
	sb.append( "    }\n" );
	sb.append( "}\n\n" );

	// toString function
	sb.append( "/**\n" );
	sb.append( " * @brief Convert a VisVersion to its string representation\n" );
	sb.append( " * @param version The VISVersion enum value to convert\n" );
	sb.append( " * @return String representation of the version\n" );
	sb.append( " */\n" );
	sb.append( "constexpr std::string_view toString( VISVersion version )\n" );
	sb.append( "{\n" );
	sb.append( "    switch ( version )\n" );
	sb.append( "    {\n" );

	for ( const auto& version : versions )
	{
		std::string enumName = version;
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "        case VISVersion::v{}:\n", enumName );
		std::format_to( std::back_inserter( sb ), "            return \"{}\";\n", version );
	}

	sb.append( "    default:\n" );
	sb.append( "        throw std::invalid_argument( \"Invalid VISVersion enum value\" );\n" );
	sb.append( "    }\n" );
	sb.append( "}\n\n" );

	// fromString function with out-parameter (bool return)
	sb.append( "/**\n" );
	sb.append( " * @brief Parse string to VISVersion enum value\n" );
	sb.append( " * @details Converts string representation to enum value (e.g., \"3-9a\" -> VISVersion::v3_9a)\n" );
	sb.append( " * @param version String representation of the version (e.g., \"3-9a\")\n" );
	sb.append( " * @param result Reference to store the parsed VISVersion enum value if successful\n" );
	sb.append( " * @return true if parsing succeeded, false otherwise\n" );
	sb.append( " * @note This function is marked [[nodiscard]] - the return value should not be ignored\n" );
	sb.append( " */\n" );
	sb.append( "[[nodiscard]] constexpr bool fromString( std::string_view version, VISVersion& result ) noexcept\n" );
	sb.append( "{\n" );

	for ( const auto& version : versions )
	{
		std::string enumName = version;
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "    if ( version == \"{}\" )\n", version );
		sb.append( "    {\n" );
		std::format_to( std::back_inserter( sb ), "        result = VISVersion::v{};\n", enumName );
		sb.append( "        return true;\n" );
		sb.append( "    }\n" );
	}

	sb.append( "    return false;\n" );
	sb.append( "}\n\n" );

	// fromString function with std::optional return
	sb.append( "/**\n" );
	sb.append( " * @brief Parse string to VISVersion (optional return overload)\n" );
	sb.append( " * @details Converts string representation to enum value (e.g., \"3-9\" -> VISVersion::v3_9a)\n" );
	sb.append( " * @param version String representation of the version (e.g., \"3-9a\")\n" );
	sb.append( " * @return Optional containing VISVersion if successful, std::nullopt otherwise\n" );
	sb.append( " * @note This function is marked [[nodiscard]] - the return value should not be ignored\n" );
	sb.append( " */\n" );
	sb.append( "[[nodiscard]] constexpr std::optional<VISVersion> fromString( std::string_view version ) noexcept\n" );
	sb.append( "{\n" );

	for ( const auto& version : versions )
	{
		std::string enumName = version;
		std::replace( enumName.begin(), enumName.end(), '-', '_' );
		std::format_to( std::back_inserter( sb ), "    if ( version == \"{}\" )\n", version );
		std::format_to( std::back_inserter( sb ), "        return VISVersion::v{};\n", enumName );
	}

	sb.append( "    return std::nullopt;\n" );
	sb.append( "}\n\n" );

	sb.append( "} // namespace VISVersions\n\n" );
	sb.append( "} // namespace dnv::vista::sdk\n" );

	std::ofstream outputFile( outputPath, std::ios::binary );
	if ( !outputFile )
	{
		fprintf( stderr, "Failed to open output file: %s\n", outputPath.string().c_str() );
		return false;
	}

	auto& buffer = lease.buffer();
	outputFile.write( buffer.data(), static_cast<std::streamsize>( buffer.size() ) );
	
	if ( !outputFile )
	{
		fprintf( stderr, "Failed to write to output file: %s\n", outputPath.string().c_str() );
		return false;
	}

	return true;
}

int main( int argc, char* argv[] )
{
	if ( argc < 3 )
	{
		fprintf( stderr, "Usage: VISVersionsGenerator <output_path> <sdk_version>\n" );
		return 1;
	}

	fs::path visVersionHeaderPath = argv[1];
	std::string_view sdkVersion = argv[2];

	printf( "Loading VIS versions from embedded resources...\n" );

	auto versions = EmbeddedResource::visVersions();

	if ( versions.empty() )
	{
		fprintf( stderr, "No VIS versions found!\n" );
		return 1;
	}

	std::sort( versions.begin(), versions.end(), []( const std::string& a, const std::string& b ) {
		return nfx::string::naturalCompare( a, b ) < 0;
	} );

	printf( "Found %zu VIS versions:\n", versions.size() );
	for ( const auto& version : versions )
	{
		printf( "  - %s\n", version.c_str() );
	}

	printf( "Generating header: %s\n", visVersionHeaderPath.string().c_str() );

	if ( !generateVISVersionHeader( versions, visVersionHeaderPath, sdkVersion ) )
	{
		return 1;
	}

	printf( "Success!\n" );
	return 0;
}
